# “publish” is the directory to publish (relative to root of your repo),
# “command” is your build command,
# “base” is directory to change to before starting build.
#
# If you set base, then that is where we will look for
# package.json/.nvmrc/etc. not repo root!

[build]
  publish = "dist"
  command = "gulp deploy"

[context.production.environment]
  HUGO_VERSION = "0.53"
  NODE_VERSION = "10.16.0"
  YARN_VERSION = "1.16.0"
