title = "AR World Travels"
baseURL = "/"

languageCode = "en-us"
languageLang = "en"

[taxonomies]
destination = "destinations"

[permalinks]
journal = "/destinations/:slug/"

[outputs]
home = ["HTML"]
page = ["HTML"]
